export default {
	friends: function(){
		let friendarr=[{
			id: 1,
			imgurl: 'sun.png',
			tip:2200,
			email: 'gold9450412@gmail.com',
			name:'小屁',
			time: new Date(),
			news: '哈囉,我好怕找工作,可是我還是想要找到工作才能賺大錢啊,哈哈哈',
		},
		{
			id: 2,
			imgurl: 'sun.png',
			tip:0,
			name:'大屁2世',
			email: 'apple12345@gmail.com',
			time: new Date(),
			news: '哈囉,我這裡有份工作給你賺大錢喔,哈哈哈',
		},
		{
			id: 3,
			imgurl: 'sun.png',
			tip:60,
			name:'中屁',
			email: 'goldapple@gmail.com',
			time: new Date(),
			news: '爽啦,爽到歪頭',
		},
		{
			id: 4,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'yeeeeeeee@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 5,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'pupupu@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 6,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'yayaya@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 7,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'vb@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 8,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'xc@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 9,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'adsa@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 10,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'asd@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 11,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'hahaha@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 12,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'mmm9450412@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 13,
			imgurl: 'sun.png',
			tip:7,
			name:'又大又中屁',
			email: 'm9450412@gmail.com',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		{
			id: 14,
			imgurl: 'sun.png',
			tip:7,
			email: 'apple9450412@gmail.com',
			name:'又大又中屁',
			time: new Date(),
			news: '耶耶,屁屁',
		},
		];
		
		return friendarr;
	},
	
	isFriend: function(){
		let isfriend=[
		{
			userid:1,
			friend:2,
		},
		{
			userid:1,
			friend:5,
		},]
		return isfriend;
	},
	
	message:function(){ //b為自己
		let msg=[
			{
				id:'a',
				imgurl:'sun.png',
				message:{
					name:'102大樓',
					address:'台北',
					latitude:31.191498,
					longitude:121.387949,
				},
				types:3,
				time:new Date(),
				tip:9,
			},
			{
				id:'b',
				imgurl:'sun.png',
				message:{
					name:'101大樓',
					address:'台北',
					latitude:31.191498,
					longitude:121.387949,
				},
				types:3,
				time:new Date()-150,
				tip:8,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:{
					voice:'a',
					time:60,
				},
				types:2,
				time:new Date()-180,
				tip:7,
			},
			{
				id:'b',
				imgurl:'sun.png',
				message:{
					voice:'a',
					time:20,
				},
				types:2,
				time:new Date()-200,
				tip:8,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:'測試測試 ',
				types:0,
				time:new Date()-500,
				tip:0,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:'測試測試,用力測試測試測試,用力測試測試測試,用力測試測試測試,用力測試測試測試,用力測試',
				types:0,
				time:new Date()-1000,
				tip:1,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:'測試測試,用力測試測試測試,用力測試測試測試,用力測試測試測試,用力測試測試測試,用力測試',
				types:0,
				time:new Date()-1000*16,
				tip:2,
			},
			{
				id:'b',
				imgurl:'sun.png',
				message:'測試測試,用力測試測試測試,用力測試測試測試,用力測試測試測試,用力測試測試測試,用力測試',
				types:0,
				time:new Date()-1000*60*60*24,
				tip:3,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:'sun.png',
				types:1,
				time:new Date()-1000*60*60*24*5,
				tip:4,
			},
			{
				id:'b',
				imgurl:'sun.png',
				message:'panda.png',
				types:1,
				time:new Date()-1000*60*60*24*5,
				tip:5,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:'cute.png',
				types:1,
				time:new Date()-1000*60*60*24*9,
				tip:6,
			},
			{
				id:'a',
				imgurl:'sun.png',
				message:'hkkkkkkk',
				types:0,
				time:new Date()-1000*60*60*24*9-2*60*1000,
				tip:6,
			},
		]
		return msg;
	}
}